site_name: دوره MBA - گروه 13
site_url: https://AttackThwarter.github.io/MBA-Course
repo_url: https://github.com/AttackThwarter/MBA-Course
edit_uri: edit/main/docs/

theme:
  name: material
  language: fa
  direction: rtl
  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: حالت شب
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: حالت روز
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

nav:
  - خانه: index.md
  - مدیریت استراتژیک:
      - مدیریت عمومی: strategy/general.md
      - برنامه ریزی استراتژیک: strategy/planning.md
      - طراحی مدل کسب و کار: strategy/business-model.md
  - بازاریابی و فروش:
      - مدیریت بازاریابی: marketing/marketing-mgmt.md
      - مدیریت فروش: marketing/sales.md
      - مدیریت تبلیغات: marketing/ads.md
      - مدیریت برند: marketing/branding.md
      - مدیریت ارتباط با مشتری: marketing/crm.md
      - دیجیتال مارکتینگ: marketing/digital.md
  - منابع انسانی و رفتار:
      - رفتار سازمانی: hr/ob.md
      - مدیریت منابع انسانی: hr/hrm.md
      - قانون کار: hr/labor-law.md
  - مهارت‌های نرم:
      - بیان و سخنوری: skills/speaking.md
      - مهارت‌های ارتباطی: skills/communication.md
      - مهارت‌های مذاکره: skills/negotiation.md
      - زبان بدن: skills/body-language.md
  - مالی و اقتصادی:
      - مدیریت مالی: finance/financial.md
      - اقتصاد کاربردی: finance/economics.md
  - مدیریت پروژه:
      - مدیریت پروژه: project/pm.md
      - پروژه پایانی: project/final-project.md


extra_css:
  - stylesheets/extra.css